language: java

env:
 - SCALA_VERSION=2.10.5
 - SCALA_VERSION=2.11.7

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7

before_script:
 - ./mvnw -version

script: ./mvnw source:jar scala:doc-jar install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
