language: java

matix:
  include:
    - env: SCALA_VERSION=2.10.6
      jdk: oraclejdk8
    - env: SCALA_VERSION=2.10.6
      jdk: oraclejdk7
    - env: SCALA_VERSION=2.10.6
      jdk: openjdk7
    - env: SCALA_VERSION=2.11.11
      jdk: oraclejdk8
    - env: SCALA_VERSION=2.11.11
      jdk: oraclejdk7
    - env: SCALA_VERSION=2.11.11
      jdk: openjdk7
    - env: SCALA_VERSION=2.12.2
      jdk: oraclejdk8

before_script: 
 - ./mvnw -version

script:
 - ./mvnw source:jar scala:doc-jar install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
