language: java

jdk:
  - oraclejdk8
  - openjdk7

env: 
  - SCALA_VERSION=2.10.7
  - SCALA_VERSION=2.11.12
  - SCALA_VERSION=2.12.6

matrix:
  exclude:
    - jdk: openjdk7
      env: SCALA_VERSION=2.12.6

before_script: 
- mvn -N io.takari:maven:0.6.1:wrapper -Dmaven=3.5.4


script:
- ./mvnw source:jar scala:doc-jar install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
