language: java

jdk:
  - openjdk8
  - openjdk11

script:
- ./millw _buildAll
- ./millw _test

after_failure:
- cat out/mill-worker-1/logs 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
