language: java

jdk:
  - oraclejdk8
  - openjdk8


before_script: 
- curl -L https://github.com/lihaoyi/mill/releases/download/0.2.8/0.2.8 > mill
- ls -la mill
- git clone --depth 1 https://github.com/lefou/mill-osgi.git
- (cd mill-osgi && sh ../mill _install)

script:
- sh mill _buildAll
- sh mill _test

after_failure:
- cat out/mill-worker-1/logs 


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
