language: java

jdk:
  - openjdk8
  - openjdk11

script:
- ./millw -i -j 0 __.compile
- ./millw -i -j 0 __.testCached

after_failure:
- cat out/mill-worker-*/logs 

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
