language: java

env:
 - SCALA_VERSION=2.10.6 JDK=oraclejdk8
 - SCALA_VERSION=2.10.6 JDK=oraclejdk7
 - SCALA_VERSION=2.10.6 JDK=openjdk7
 - SCALA_VERSION=2.11.11 JDK=oraclejdk8
 - SCALA_VERSION=2.11.11 JDK=oraclejdk7
 - SCALA_VERSION=2.11.11 JDK=openjdk7
 - SCALA_VERSION=2.12.2 JDK=oraclejdk8

script:
 - jdk_switcher use ${JDK} 
 - ./mvnw -version
 - ./mvnw source:jar scala:doc-jar install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
