language: java

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7

before_script:
 - ./mvnw -version
 - sbt -sbt-version 0.13.8 +test +osgiBundle

script: ./mvnw source:jar scala:doc-jar install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b10437ef097d33525197
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
