language: java

env:
 - SCALA_VERSION=2.10.5
 - SCALA_VERSION=2.11.6

jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7
 - openjdk6

install:
 - wget "http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz"
 - tar xzf apache-maven-3.3.3-bin.tar.gz
 - export MVN_HOME="$(pwd)/apache-maven-3.3.3"

before_script:
 - ./apache-maven-3.3.3/bin/mvn -version
 - mvn -version

script: ./apache-maven-3.3.3/bin/mvn package
