= Domino

image:https://travis-ci.org/domino-osgi/domino.svg?branch=master["Travis CI Build Status", link="https://travis-ci.org/domino-osgi/domino"]
image:https://www.codacy.com/project/badge/afcdfefe80494be4bf729437dc3e2a9b["Codacy code quality", link="https://www.codacy.com/app/lefou/domino"]
image:https://badges.gitter.im/Join%20Chat.svg["Gitter chat", link="https://gitter.im/domino-osgi/domino?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge"]

Domino is a small library for the programming language http://www.scala-lang.org[Scala] designed to support developers in writing http://www.osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleActivator.html[bundle activators] for the Java module system http://www.osgi.org/Technology/WhyOSGi[OSGi]. It strives to make writing complex and highly-dynamic bundle activators as easy as possible without sacrificing the power of the OSGi API.

As such, Domino is a lightweight alternative to OSGi component models like http://ipojo.org[iPOJO], http://wiki.osgi.org/wiki/Blueprint[Blueprint] and http://wiki.osgi.org/wiki/Declarative_Services[Declarative Services]. Especially for those who want to leverage the power of pure code instead of reverting to an XML- or annotation-based approach.

== Examples

=== Wait for service and register service 

[source,scala]
----
import domino.DominoActivator
import org.osgi.service.http.HttpService

class MyService(httpService: HttpService)

class Activator extends DominoActivator {
  whenBundleActive {
    // Make service available as long as another 
    // service is present
    whenServicePresent[HttpService] { httpService =>
      val myService = new MyService(httpService)
      myService.providesService[MyService]
    }
  }
}
----

=== Listen for configuration updates

[source,scala]
----
import domino.DominoActivator

class KeyService(key: String)

class Activator extends DominoActivator {
  whenBundleActive {
    // Reregister service whenever configuration changes
    whenConfigurationActive("my_service") { conf =>
      val key = conf.getOrElse("key", "defaultKey")
      new KeyService(key).providesService[KeyService]
    }
  }
}
----

== Further reading

Learn more on http://www.helgoboss.org/projects/domino/[Domino's OLD project website].

== Building Domino

Domino is build with Apache Maven and the Polygot Scala Extension. At least Maven 3.3.1 is required.

To cleanly build domino, use:

----
mvn clean package
----


To build domino for another Scala version, e.g. 2.11.6 (under a Unix-like OS), use:

----
SCALA_VERSION=2.11.6 mvn clean package
----

== Creating a Release

* Bump version in pom file
* Update Changelog
* Review documentation
* Create a git tag with the version
* Upload the release artifacts up to Maven Central

=== Deploy to Maven Central / Sonatype Open Source Respository (OSSRH)

Unfortunately, not all Maven plugins are ready yet for a Polyglot Maven setup, thus the current version 1.6.3 of the Maven Staging Plugin simply doen't work.

To deploy a release to , use the shell script `makerelase.sh`.

Please review the variables in the script, namely the `DOMINO_VERSION` and the `SCALA_VERSIONS`.

When executed the script will create a `staging-settings.xml` (to which you should add your login credentials) and wait. After pressing enter it will build all artifatcs and upload them to the OSSRH Nexus where you must log-in and manually release these artifacts.


== Changelog

=== Domino 1.1.0 - __not released yet__

* Switched Maintainer to Tobias Roeser
* Renamed base package from `org.helgoboss.domino` to `domino`
* Embedded former dependencies (`org.helgoboss.capsule`, `org.helgoboss.scala-osgi-metatype`, `org.helgoboss.scala-logging`) as sub packages
* Switched to Polyglot Scala extension for Maven 3.3
* Cross-Release for Scala 2.10 and 2.11

=== Domino 1.0.0 - 2013-03-31

* Initial release for Scala 2.10
