name: Build and Test

on:
  push:
  pull_request:

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - run: ./mill __.compile + __.test + __.publishLocal testrepo
